apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: launchpad-builder
  annotations:
    description: This template creates a Build Configuration using an S2I builder.
    tags: instant-app
parameters:
  - name: SUFFIX_NAME
    description: The suffix name for the template objects
    displayName: Suffix name
    value: ''
  - name: RELEASE_VERSION
    description: The release version number of application
    displayName: Release version
    value: 3.0.0
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: master
    required: true
  - name: GITHUB_WEBHOOK_SECRET
    description: A secret string used to configure the GitHub webhook.
    displayName: GitHub Webhook Secret
    required: true
    from: '[a-zA-Z0-9]{40}'
    generate: expression
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: 'nodejs-rest-http-redhat${SUFFIX_NAME}'
      labels:
        version: '${RELEASE_VERSION}'
    spec: {}
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: runtime-ubi8-nodejs-10
    spec:
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: registry.access.redhat.com/ubi8/nodejs-12
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: 'nodejs-rest-http-redhat-s2i${SUFFIX_NAME}'
      labels:
        version: '${RELEASE_VERSION}'
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'nodejs-rest-http-redhat${SUFFIX_NAME}:${RELEASE_VERSION}'
      postCommit: {}
      resources: {}
      source:
        git:
          uri: '${SOURCE_REPOSITORY_URL}'
          ref: '${SOURCE_REPOSITORY_REF}'
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'runtime-ubi8-nodejs-10:latest'
          incremental: true
      triggers:
        - github:
            secret: '${GITHUB_WEBHOOK_SECRET}'
          type: GitHub
        - type: ConfigChange
    status:
      lastVersion: 0
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        expose: 'true'
        project: nodejs-rest-http-redhat
        provider: nodeshift
        version: '${RELEASE_VERSION}'
      name: 'nodejs-rest-http-redhat${SUFFIX_NAME}'
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        project: nodejs-rest-http-redhat
        provider: nodeshift
      type: ClusterIP
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: 'nodejs-rest-http-redhat${SUFFIX_NAME}'
      labels:
        app: nodejs-rest-http-redhat
        provider: nodeshift
        project: nodejs-rest-http-redhat
        version: '${RELEASE_VERSION}'
    spec:
      template:
        spec:
          containers:
            - readinessProbe:
                httpGet:
                  path: /api/greeting
                  port: 8080
                  scheme: HTTP
              livenessProbe:
                httpGet:
                  path: /api/greeting
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 30
              image: ''
              name: nodejs-rest-http-redhat
              securityContext:
                privileged: false
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
        metadata:
          labels:
            app: nodejs-rest-http-redhat
            project: nodejs-rest-http-redhat
            provider: nodeshift
            version: '${RELEASE_VERSION}'
      replicas: 1
      selector:
        app: nodejs-rest-http-redhat
        project: nodejs-rest-http-redhat
        provider: nodeshift
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - nodejs-rest-http-redhat
            from:
              kind: ImageStreamTag
              name: 'nodejs-rest-http-redhat${SUFFIX_NAME}:${RELEASE_VERSION}'
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        project: nodejs-rest-http-redhat
        provider: nodeshift
        version: '${RELEASE_VERSION}'
      name: 'nodejs-rest-http-redhat${SUFFIX_NAME}'
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: 'nodejs-rest-http-redhat${SUFFIX_NAME}'
